name: network_util
description: Handle network devices - made easy
version: 0.1.1

publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # dart_ping: ^7.0.1
  http: any
  log_message:
    git:
      url: https://github.com/Marc-R2/logger_dart.git

dev_dependencies:
  stream_channel: ^2.1.1
  test: ^1.21.5
  very_good_analysis: ^3.0.1
